---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bdeh8989/augustineprod/
    - /bin/cp -R backend $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
