# https://help.github.com/en/actions
name: CI actions for backend

on: [push]

jobs:
  tests:
    name: Running tests
    runs-on: ubuntu-20.04
    steps:
      # —— Check Repo 🔎 ——————————————————————————————————————————————
      - name: Checkout
        uses: actions/checkout@v2
      # —— Install Node 16 🔎 ——————————————————————————————————————————————
      - name: Setup Node
        uses: actions/setup-node@v1
        with: 
          node-version:16.13.0
      # —— Install dependencies🔎 ——————————————————————————————————————————————
      - name: Install dependencies
        run: npm install
      # —— Run tests🔎 ——————————————————————————————————————————————
      - name: Run tests
        run: npm test
      