/* eslint-disable */
export const SET_OPEN_SMALL_SCREEN_NAV = 'SET_OPEN_SMALL_SCREEN_NAV'
export const SET_ACTIVE_RUBRIC = 'SET_ACTIVE_RUBRIC'
export const SET_ROUTES = 'SET_ROUTES'
export const SET_CATEGORY_ASIDE = 'SET_CATEGORY_ASIDE'
export const SET_URL_PREFIX = 'SET_URL_PREFIX'
