/* eslint-disable */
export const SET_OPEN_SMALL_SCREEN_NAV = 'SET_OPEN_SMALL_SCREEN_NAV'
export const SET_CATEGORY_ASIDE = 'SET_CATEGORY_ASIDE'
export const SET_URL_PREFIX = 'SET_URL_PREFIX'
export const SET_MAIN_DIALOG_DATAS = 'SET_MAIN_DIALOG_DATAS'
export const SET_MAIN_DIALOG_COUNT = 'SET_MAIN_DIALOG_COUNT'
