const Equipe = [
  {
    genre: 'monsieur',
    firstname: 'Daniel',
    lastname: 'Lachal',
    entites: ['apel'],
    roles: ['parent benevole'],
    mission: [],
    classes: ['toutes'],
    isAdmin: false,
    isModerator: false,
  },
  {
    genre: 'madame',
    firstname: 'Emmanuelle',
    lastname: 'rouard',
    entites: ['inspection academique'],
    roles: ['enseignant'],
    mission: 'enseignant',
    classes: ['cm2'],
    isAdmin: false,
    isModerator: false,
  },
  {
    genre: 'monsieur',
    firstname: 'frederic',
    lastname: 'cintas',
    entites: ['inspection academique', 'ogec'],
    roles: ['enseignant'],
    mission: 'directeur',
    classes: ['cm1'],
    isAdmin: true,
    isModerator: false,
  },
  {
    genre: 'madame',
    firstname: 'Stephanie',
    lastname: 'malet marechal',
    entites: ['inspection academique'],
    roles: ['enseignant'],
    mission: 'enseignant',
    classes: ['cm1', 'ms'],
    isAdmin: false,
    isModerator: false,
  },
  {
    genre: 'madame',
    firstname: 'Beatrice',
    lastname: 'bouvier',
    entites: ['inspection academique'],
    roles: ['enseignant'],
    mission: 'enseignant',
    classes: ['ce2'],
    isAdmin: false,
    isModerator: false,
  },
  {
    genre: 'madame',
    firstname: 'Carine',
    lastname: 'budin',
    entites: ['inspection academique'],
    roles: ['enseignant'],
    mission: 'enseignant',
    classes: ['ce1'],
    isAdmin: false,
    isModerator: false,
  },
  {
    genre: 'madame',
    firstname: 'Kelly',
    lastname: 'grosjean',
    entites: ['inspection academique'],
    roles: ['enseignant'],
    mission: 'enseignant',
    classes: ['cp'],
    isAdmin: false,
    isModerator: false,
  },
  {
    genre: 'madame',
    firstname: 'Patricia',
    lastname: 'guerin',
    entites: ['inspection academique'],
    roles: ['enseignant'],
    mission: 'enseignant',
    classes: ['gs'],
    isAdmin: false,
    isModerator: false,
  },
  {
    genre: 'madame',
    firstname: 'Flore',
    lastname: 'lheriteau',
    entites: ['inspection academique'],
    roles: ['enseignant'],
    mission: 'enseignant',
    classes: ['ms'],
    isAdmin: false,
    isModerator: false,
  },
  {
    genre: 'madame',
    firstname: 'Blandine',
    lastname: 'goujet',
    entites: ['inspection academique'],
    roles: ['enseignant'],
    mission: 'enseignant',
    classes: ['ps'],
    isAdmin: false,
    isModerator: false,
  },
  {
    genre: 'madame',
    firstname: 'Veronique',
    lastname: 'cretinon',
    entites: ['inspection academique'],
    roles: ['enseignant'],
    mission: 'enseignant specialisé',
    classes: ['++'],
    isAdmin: false,
    isModerator: false,
  },
  {
    genre: 'madame',
    firstname: '',
    lastname: 'geay',
    entites: ['ogec'],
    roles: ['aide cuisinière'],
    mission: '',
    classes: [],
    isAdmin: false,
    isModerator: false,
  },
  {
    genre: 'madame',
    firstname: '',
    lastname: 'landry',
    entites: ['ogec'],
    roles: [`agent d'entretien`],
    mission: '',
    classes: [],
    isAdmin: false,
    isModerator: false,
  },
  {
    genre: 'madame',
    firstname: 'Sophie',
    lastname: 'marguet',
    entites: ['ogec'],
    roles: [`aide maternelle`, `surveillante`],
    mission: '',
    classes: [],
    isAdmin: false,
    isModerator: false,
  },
  {
    genre: 'madame',
    firstname: 'Carmen',
    lastname: 'saby',
    entites: ['ogec'],
    roles: [`aide maternelle`, `surveillante`],
    mission: '',
    classes: [],
    isAdmin: false,
    isModerator: false,
  },
  {
    genre: 'madame',
    firstname: 'Monique',
    lastname: 'duperron',
    entites: ['ogec'],
    roles: [`aide pedagogique`],
    mission: '',
    classes: [],
    isAdmin: false,
    isModerator: false,
  },
  {
    genre: 'madame',
    firstname: 'Corine',
    lastname: 'rius',
    entites: ['ogec'],
    roles: [`avs`, `surveillante`],
    mission: '',
    classes: [],
    isAdmin: false,
    isModerator: false,
  },
  {
    genre: 'madame',
    firstname: 'Christine',
    lastname: 'chaloin',
    entites: ['ogec'],
    roles: [`secretaire`, `surveillante`],
    mission: '',
    classes: [],
    isAdmin: false,
    isModerator: false,
  },
]

export default Equipe
