export const SET_PRIVATE_ACCOUNT_DATA_ALERT = 'SET_PRIVATE_ACCOUNT_DATA_ALERT'
export const SET_PRIVATE_ACCOUNT_MUTATE_ALERT =
  'SET_PRIVATE_ACCOUNT_MUTATE_ALERT'
export const SET_INFORMATIONS_INSCRIPTIONS_ALERT =
  'SET_INFORMATIONS_INSCRIPTIONS_ALERT'
export const SET_ALBUM_MUTATE_ALERT = 'SET_ALBUM_MUTATE_ALERT'
export const SET_ALBUM_FETCH_ALERT = 'SET_ALBUM_FETCH_ALERT'
export const SET_ALBUM_PAGE_MUTATE_ALERT = 'SET_ALBUM_PAGE_MUTATE_ALERT'
export const SET_ALBUM_PAGE_FETCH_ALERT = 'SET_ALBUM_PAGE_FETCH_ALERT'
export const SET_PAPER_FETCH_ALERT = 'SET_PAPER_FETCH_ALERT'
export const SET_PAPER_MUTATE_ALERT = 'SET_PAPER_MUTATE_ALERT'
export const SET_LOGIN_ALERT = 'SET_LOGIN_ALERT'
export const SET_REGISTER_ALERT = 'SET_REGISTER_ALERT'
