export const SET_PRIVATE_ACCOUNT_DATA_ALERT = 'SET_PRIVATE_ACCOUNT_DATA_ALERT'
export const SET_PRIVATE_ACCOUNT_MUTATE_ALERT =
  'SET_PRIVATE_ACCOUNT_MUTATE_ALERT'
export const SET_INFORMATIONS_INSCRIPTIONS_ALERT =
  'SET_INFORMATIONS_INSCRIPTIONS_ALERT'
export const SET_ALBUM_MUTATE_ALERT = 'SET_ALBUM_MUTATE_ALERT'
